# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zex33GANsiShwoOs2vCQ54P2JnpnOUH
"""

from flask import Flask, request, jsonify
from transformers import pipeline

# Initialize Flask app
app = Flask(__name__)

# Load sentiment analysis pipeline
classifier = pipeline("sentiment-analysis")

@app.route("/")
def home():
    return "for testing api running."

@app.route("/predict-text", methods=["POST"])
def predict_text():
    data = request.get_json()

    if not data or 'text' not in data:
        return jsonify({"error": "provide text in JSON body."}), 400

    text = data['text']
    result = classifier(text)[0]

    response = {
        "sucess": True,
        "label": result['label'],
        "confidence": round(result['score'], 4)
    }
    return jsonify(response)

if __name__ == "__main__":
    app.run(debug=True)